version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - cd functionRead
      - npm install
      - cd ../functionWrite
      - npm install
      - cd ../functionDelete
      - npm install
      - cd ..
  build:
    commands:
      - sam package
        --template-file template.yml
        --output-template-file package.yml
        --s3-bucket demo-ci-cd-sam-bucket-000000000000
artifacts:
  files:
    - package.yml
